import { useScrollReveal } from '@/hooks/useScrollReveal';
import { FileText, Palette, MessageSquare, Sparkles } from 'lucide-react';

const demoItems = [
  {
    icon: FileText,
    title: "AI-Generated Business Plan",
    description: "Complete executive summary, market analysis, financial projections, and growth strategy",
    image: "/demo-business-plan.jpg",
    gradient: "from-purple-600 to-blue-600",
  },
  {
    icon: Palette,
    title: "Branding Ideas & Concepts",
    description: "Brand names, logo concepts, color palettes, and visual identity guidelines",
    image: "/demo-branding.jpg",
    gradient: "from-pink-600 to-purple-600",
  },
  {
    icon: MessageSquare,
    title: "Content & Marketing Copy",
    description: "Social media posts, ad copy, email sequences, and product descriptions",
    image: "/demo-content.jpg",
    gradient: "from-cyan-600 to-blue-600",
  },
];

export function Demo() {
  const headerRef = useScrollReveal<HTMLDivElement>();
  const demosRef = useScrollReveal<HTMLDivElement>();

  return (
    <section className="relative py-24 px-4 sm:px-6 lg:px-8 overflow-hidden">
      {/* Background Effects */}
      <div className="absolute inset-0 bg-grid opacity-30" />
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-neon-purple/5 rounded-full blur-[200px]" />

      <div className="relative z-10 max-w-7xl mx-auto">
        {/* Section Header */}
        <div ref={headerRef} className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass-card mb-6">
            <Sparkles className="w-4 h-4 text-neon-purple" />
            <span className="text-sm font-medium text-gray-300">Real AI Output Examples</span>
          </div>
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-bold text-white mb-4">
            See The <span className="gradient-text">Magic</span> Happen
          </h2>
          <p className="text-gray-400 text-lg max-w-2xl mx-auto">
            These are actual outputs generated by our prompts. 
            Imagine what AI can create for YOUR business.
          </p>
        </div>

        {/* Demo Cards */}
        <div 
          ref={demosRef}
          className="grid grid-cols-1 lg:grid-cols-3 gap-8 reveal-stagger"
        >
          {demoItems.map((item, index) => (
            <div
              key={index}
              className="glass-card rounded-3xl overflow-hidden reveal-item group hover:border-neon-purple/40 transition-all duration-500"
            >
              {/* Image Container */}
              <div className="relative h-56 overflow-hidden">
                {/* Gradient Background (as placeholder for demo images) */}
                <div className={`absolute inset-0 bg-gradient-to-br ${item.gradient} opacity-80`} />
                <div className="absolute inset-0 bg-[url('data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNDAiIGhlaWdodD0iNDAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+PGNpcmNsZSBjeD0iMjAiIGN5PSIyMCIgcj0iMSIgZmlsbD0id2hpdGUiIGZpbGwtb3BhY2l0eT0iMC4xIi8+PC9zdmc+')] opacity-30" />
                
                {/* Mock Content Overlay */}
                <div className="absolute inset-0 flex items-center justify-center p-6">
                  <div className="w-full max-w-xs">
                    <div className="glass-card rounded-xl p-4 transform group-hover:scale-105 transition-transform duration-500">
                      <div className="flex items-center gap-3 mb-3">
                        <div className={`w-8 h-8 rounded-lg bg-gradient-to-br ${item.gradient} flex items-center justify-center`}>
                          <item.icon className="w-4 h-4 text-white" />
                        </div>
                        <div className="h-3 w-24 bg-white/20 rounded" />
                      </div>
                      <div className="space-y-2">
                        <div className="h-2 w-full bg-white/10 rounded" />
                        <div className="h-2 w-4/5 bg-white/10 rounded" />
                        <div className="h-2 w-3/5 bg-white/10 rounded" />
                      </div>
                    </div>
                  </div>
                </div>

                {/* Glow Effect */}
                <div className="absolute inset-0 bg-gradient-to-t from-dark-slate via-transparent to-transparent" />
              </div>

              {/* Content */}
              <div className="p-6">
                <div className="flex items-center gap-3 mb-3">
                  <div className={`w-10 h-10 rounded-xl bg-gradient-to-br ${item.gradient} flex items-center justify-center`}>
                    <item.icon className="w-5 h-5 text-white" />
                  </div>
                  <h3 className="text-lg font-bold text-white group-hover:text-neon-purple transition-colors">
                    {item.title}
                  </h3>
                </div>
                <p className="text-gray-400 text-sm leading-relaxed">
                  {item.description}
                </p>
              </div>
            </div>
          ))}
        </div>

        {/* Trust Badge */}
        <div className="text-center mt-12">
          <div className="inline-flex items-center gap-4 glass-card rounded-full px-6 py-3">
            <div className="flex -space-x-2">
              {[...Array(3)].map((_, i) => (
                <div
                  key={i}
                  className="w-8 h-8 rounded-full bg-gradient-to-br from-neon-purple to-neon-blue border-2 border-dark-slate"
                />
              ))}
            </div>
            <span className="text-gray-300 text-sm">
              <span className="text-white font-semibold">2,500+</span> entrepreneurs trust our prompts
            </span>
          </div>
        </div>
      </div>
    </section>
  );
}
